apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdefk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rdefk
  template:
    metadata:
      labels:
        app: rdefk
    spec:
      containers:
      - image: okteto.dev/rdefk:latest
        name: rdefk
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "4eeeabe5-4875-461d-a8fc-683c8622a5c4"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "4eeeabe5-4875-461d-a8fc-683c8622a5c4"
        - name: Vmess_Path
          value: "/vmkm66c6"
        - name: Share_Path
          value: "/v2link"
